"""Deployment skills — policy packaging, deployment, and validation."""

import textwrap


def package_policy(
    policy_name: str = "cr10_smoothing",
    model_path: str = "checkpoints/latest.pt",
    config_files: list[str] | None = None,
) -> str:
    """Generate a policy packaging script that bundles model + configs for deployment."""
    if config_files is None:
        config_files = [
            "config/cr10_curobo.yaml",
            "config/cr10_collision_spheres.yaml",
            "config/cr10_world.yaml",
        ]
    configs_str = ",\n        ".join(f'"{c}"' for c in config_files)
    return textwrap.dedent(f"""\
    #!/usr/bin/env python3
    \"\"\"Package policy '{policy_name}' for deployment.

    Bundles model checkpoint, configs, and metadata into a deployment artifact.

    Generated by skills/deployment.py
    \"\"\"

    import os
    import json
    import shutil
    import hashlib
    from datetime import datetime

    POLICY_NAME = "{policy_name}"
    MODEL_PATH = "{model_path}"
    CONFIG_FILES = [
        {configs_str}
    ]
    OUTPUT_DIR = f"deployments/{{POLICY_NAME}}"


    def compute_sha256(path: str) -> str:
        h = hashlib.sha256()
        with open(path, "rb") as f:
            for chunk in iter(lambda: f.read(8192), b""):
                h.update(chunk)
        return h.hexdigest()


    def package():
        os.makedirs(OUTPUT_DIR, exist_ok=True)

        manifest = {{
            "name": POLICY_NAME,
            "packaged_at": datetime.now().isoformat(),
            "files": {{}},
        }}

        # Copy model
        if os.path.exists(MODEL_PATH):
            dest = os.path.join(OUTPUT_DIR, os.path.basename(MODEL_PATH))
            shutil.copy2(MODEL_PATH, dest)
            manifest["files"]["model"] = {{
                "path": os.path.basename(MODEL_PATH),
                "sha256": compute_sha256(dest),
            }}
        else:
            print(f"WARNING: Model not found: {{MODEL_PATH}}")

        # Copy configs
        manifest["files"]["configs"] = []
        for cfg in CONFIG_FILES:
            if os.path.exists(cfg):
                dest = os.path.join(OUTPUT_DIR, os.path.basename(cfg))
                shutil.copy2(cfg, dest)
                manifest["files"]["configs"].append({{
                    "path": os.path.basename(cfg),
                    "sha256": compute_sha256(dest),
                }})
            else:
                print(f"WARNING: Config not found: {{cfg}}")

        # Write manifest
        manifest_path = os.path.join(OUTPUT_DIR, "manifest.json")
        with open(manifest_path, "w") as f:
            json.dump(manifest, f, indent=2)

        print(f"Policy '{{POLICY_NAME}}' packaged to {{OUTPUT_DIR}}/")
        print(f"  Model: {{manifest['files'].get('model', 'MISSING')}}")
        print(f"  Configs: {{len(manifest['files']['configs'])}}")


    if __name__ == "__main__":
        package()
    """)


def deploy_policy(
    policy_name: str = "cr10_smoothing",
    target_machine: str = "workstation",
    deploy_path: str = "/opt/policies",
) -> str:
    """Generate a deployment script that transfers a packaged policy to a target machine."""
    return textwrap.dedent(f"""\
    #!/usr/bin/env python3
    \"\"\"Deploy policy '{policy_name}' to {target_machine}.

    Transfers the packaged policy and validates the deployment.
    Requires human approval before executing.

    Generated by skills/deployment.py
    \"\"\"

    import os
    import json
    import subprocess

    POLICY_NAME = "{policy_name}"
    SOURCE_DIR = f"deployments/{{POLICY_NAME}}"
    TARGET_MACHINE = "{target_machine}"
    DEPLOY_PATH = "{deploy_path}"


    def validate_package() -> bool:
        manifest_path = os.path.join(SOURCE_DIR, "manifest.json")
        if not os.path.exists(manifest_path):
            print("ERROR: No manifest.json — run package_policy first")
            return False
        with open(manifest_path) as f:
            manifest = json.load(f)
        print(f"Package: {{manifest['name']}}")
        print(f"Packaged: {{manifest['packaged_at']}}")
        return True


    def deploy():
        if not validate_package():
            return

        target_dir = f"{{DEPLOY_PATH}}/{{POLICY_NAME}}"

        if TARGET_MACHINE == "workstation" or TARGET_MACHINE == "localhost":
            os.makedirs(target_dir, exist_ok=True)
            subprocess.run(["cp", "-r", f"{{SOURCE_DIR}}/.", target_dir], check=True)
        else:
            subprocess.run([
                "scp", "-r", SOURCE_DIR,
                f"samuel@{{TARGET_MACHINE}}:{{target_dir}}"
            ], check=True)

        print(f"Deployed '{{POLICY_NAME}}' to {{TARGET_MACHINE}}:{{target_dir}}")


    if __name__ == "__main__":
        print("⚠  Deployment requires human approval.")
        confirm = input(f"Deploy {{POLICY_NAME}} to {{TARGET_MACHINE}}? [y/N] ")
        if confirm.lower() == "y":
            deploy()
        else:
            print("Deployment cancelled.")
    """)


def validate_deployment(
    policy_name: str = "cr10_smoothing",
    deploy_path: str = "/opt/policies",
) -> str:
    """Generate a deployment validation script that checks integrity post-deploy."""
    return textwrap.dedent(f"""\
    #!/usr/bin/env python3
    \"\"\"Validate deployment of policy '{policy_name}'.

    Checks file integrity, config validity, and runtime compatibility.

    Generated by skills/deployment.py
    \"\"\"

    import os
    import json
    import hashlib

    POLICY_NAME = "{policy_name}"
    DEPLOY_PATH = os.path.join("{deploy_path}", POLICY_NAME)


    def compute_sha256(path: str) -> str:
        h = hashlib.sha256()
        with open(path, "rb") as f:
            for chunk in iter(lambda: f.read(8192), b""):
                h.update(chunk)
        return h.hexdigest()


    def validate():
        print(f"# Deployment Validation: {{POLICY_NAME}}")

        manifest_path = os.path.join(DEPLOY_PATH, "manifest.json")
        if not os.path.exists(manifest_path):
            print("  FAIL: manifest.json not found")
            return False

        with open(manifest_path) as f:
            manifest = json.load(f)

        all_ok = True

        # Check model file
        model_info = manifest["files"].get("model")
        if model_info:
            model_path = os.path.join(DEPLOY_PATH, model_info["path"])
            if os.path.exists(model_path):
                actual_hash = compute_sha256(model_path)
                if actual_hash == model_info["sha256"]:
                    print(f"  PASS: Model integrity OK")
                else:
                    print(f"  FAIL: Model hash mismatch")
                    all_ok = False
            else:
                print(f"  FAIL: Model file missing")
                all_ok = False

        # Check config files
        for cfg in manifest["files"].get("configs", []):
            cfg_path = os.path.join(DEPLOY_PATH, cfg["path"])
            if os.path.exists(cfg_path):
                actual_hash = compute_sha256(cfg_path)
                if actual_hash == cfg["sha256"]:
                    print(f"  PASS: {{cfg['path']}} integrity OK")
                else:
                    print(f"  FAIL: {{cfg['path']}} hash mismatch")
                    all_ok = False
            else:
                print(f"  FAIL: {{cfg['path']}} missing")
                all_ok = False

        if all_ok:
            print("\\n  Status: DEPLOYMENT VALID")
        else:
            print("\\n  Status: DEPLOYMENT INVALID — do not use")
        return all_ok


    if __name__ == "__main__":
        validate()
    """)
