"""Robotics skills — cuRobo, Isaac Sim, URDF, ROS2 code/config generators."""

import os
import textwrap
import xml.etree.ElementTree as ET


# ---------------------------------------------------------------------------
# cuRobo
# ---------------------------------------------------------------------------

def curobo_config(
    robot: str = "cr10",
    urdf_path: str = "cr10_robot.urdf",
    base_link: str = "base_link",
    ee_link: str = "Link6",
    joint_names: list[str] | None = None,
    max_acceleration: float = 10.0,
    max_jerk: float = 500.0,
) -> str:
    """Generate a cuRobo robot configuration YAML for trajectory planning."""
    if joint_names is None:
        joint_names = ["joint1", "joint2", "joint3", "joint4", "joint5", "joint6"]
    joints_yaml = "\n".join(f'        - "{j}"' for j in joint_names)
    retract = ", ".join(["0.0", "-1.5708", "1.5708", "0.0", "1.5708", "0.0"])

    return textwrap.dedent(f"""\
    # cuRobo robot configuration — {robot}
    # Generated by skills/robotics.py

    robot_cfg:
      kinematics:
        urdf_path: "{urdf_path}"
        asset_root_path: ""
        base_link: "{base_link}"
        ee_link: "{ee_link}"
        use_global_cumul: True

        collision_link_names:
          - "{base_link}"
          - "Link1"
          - "Link2"
          - "Link3"
          - "Link4"
          - "Link5"
          - "{ee_link}"

        collision_spheres: "config/cr10_collision_spheres.yaml"
        collision_sphere_buffer: 0.004

        self_collision_ignore:
          "{base_link}": ["Link1", "Link2"]
          "Link1": ["Link2", "Link3", "Link4"]
          "Link2": ["Link3", "Link4"]
          "Link3": ["Link4", "Link5", "{ee_link}"]
          "Link4": ["Link5", "{ee_link}"]
          "Link5": ["{ee_link}"]

        lock_joints: {{}}

        cspace:
          joint_names:
    {joints_yaml}
          retract_config: [{retract}]
          null_space_weight: [1.0, 1.0, 1.0, 1.0, 0.5, 0.5]
          cspace_distance_weight: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
          max_acceleration: {max_acceleration}
          max_jerk: {max_jerk}
    """)


def collision_spheres(
    link_specs: dict[str, list[dict]] | None = None,
) -> str:
    """Generate a cuRobo collision spheres YAML from link specifications."""
    if link_specs is None:
        # Default CR10 spheres
        link_specs = {
            "base_link": [
                {"center": [0.0, 0.0, 0.02], "radius": 0.08},
                {"center": [0.0, 0.0, 0.06], "radius": 0.07},
            ],
            "Link1": [
                {"center": [0.0, 0.0, 0.0], "radius": 0.07},
                {"center": [0.0, -0.01, 0.03], "radius": 0.06},
            ],
            "Link2": [
                {"center": [0.0, 0.0, 0.0], "radius": 0.065},
                {"center": [-0.15, 0.0, 0.1], "radius": 0.06},
                {"center": [-0.30, 0.0, 0.15], "radius": 0.055},
                {"center": [-0.45, 0.0, 0.18], "radius": 0.05},
                {"center": [-0.607, 0.0, 0.0], "radius": 0.05},
            ],
            "Link3": [
                {"center": [0.0, 0.0, 0.0], "radius": 0.055},
                {"center": [-0.14, 0.0, 0.03], "radius": 0.05},
                {"center": [-0.28, 0.0, 0.06], "radius": 0.05},
                {"center": [-0.42, 0.0, 0.09], "radius": 0.045},
                {"center": [-0.568, 0.0, 0.0], "radius": 0.045},
            ],
            "Link4": [
                {"center": [0.0, 0.0, 0.0], "radius": 0.05},
                {"center": [0.0, 0.005, -0.005], "radius": 0.045},
                {"center": [0.0, -0.06, 0.0], "radius": 0.04},
            ],
            "Link5": [
                {"center": [0.0, 0.0, 0.0], "radius": 0.045},
                {"center": [0.0, -0.015, -0.005], "radius": 0.04},
                {"center": [0.0, 0.05, 0.0], "radius": 0.04},
            ],
            "Link6": [
                {"center": [0.0, 0.0, 0.0], "radius": 0.035},
                {"center": [0.0, 0.0, -0.02], "radius": 0.03},
            ],
        }

    lines = ["# cuRobo collision spheres", "# Generated by skills/robotics.py", "",
             "collision_spheres:"]
    for link, spheres in link_specs.items():
        lines.append(f"  {link}:")
        for s in spheres:
            c = s["center"]
            lines.append(f"    - center: [{c[0]}, {c[1]}, {c[2]}]")
            lines.append(f"      radius: {s['radius']}")
        lines.append("")
    return "\n".join(lines)


def trajectory_smoothing(
    waypoints: list[list[float]] | None = None,
    dt: float = 0.01,
    max_velocity: float = 2.0,
    max_acceleration: float = 10.0,
    max_jerk: float = 500.0,
) -> str:
    """Generate a Python script for cuRobo trajectory smoothing on spline waypoints."""
    if waypoints is None:
        waypoints = [
            [0.0, -1.5708, 1.5708, 0.0, 1.5708, 0.0],
            [0.5, -1.2, 1.3, 0.2, 1.5, 0.1],
        ]
    wp_str = ",\n        ".join(str(w) for w in waypoints)
    return textwrap.dedent(f"""\
    #!/usr/bin/env python3
    \"\"\"cuRobo trajectory smoothing for CR10 spline paths.

    Pipeline: Cinema motion software -> Spline path -> cuRobo (smooth/validate)
              -> Joint trajectory -> Safety system -> Robot driver

    Generated by skills/robotics.py
    \"\"\"

    import torch
    import numpy as np
    from curobo.types.robot import JointState
    from curobo.wrap.reacher.motion_gen import MotionGen, MotionGenConfig

    WAYPOINTS = [
        {wp_str}
    ]
    DT = {dt}
    MAX_VELOCITY = {max_velocity}
    MAX_ACCELERATION = {max_acceleration}
    MAX_JERK = {max_jerk}


    def smooth_trajectory(waypoints, dt=DT):
        \"\"\"Smooth a spline trajectory through cuRobo's trajectory optimizer.\"\"\"
        device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

        # Load cuRobo config
        config = MotionGenConfig.load_from_robot_config(
            robot_cfg_path="config/cr10_curobo.yaml",
            world_cfg_path="config/cr10_world.yaml",
        )
        motion_gen = MotionGen(config)
        motion_gen.warmup()

        # Convert waypoints to joint states
        positions = torch.tensor(waypoints, device=device, dtype=torch.float32)

        # Use cuRobo to smooth — validates jerk/acceleration limits
        result = motion_gen.plan_batch(
            start_state=JointState(position=positions[:-1]),
            goal_state=JointState(position=positions[1:]),
        )

        if result.success.all():
            smoothed = result.get_interpolated_plan()
            print(f"Smoothed {{len(waypoints)}} waypoints -> {{smoothed.shape[0]}} points")
            print(f"Max velocity: {{smoothed.velocity.abs().max():.3f}} rad/s")
            print(f"Max acceleration: {{smoothed.acceleration.abs().max():.3f}} rad/s²")
            print(f"Max jerk: {{smoothed.jerk.abs().max():.3f}} rad/s³")
            return smoothed
        else:
            print(f"Smoothing failed for {{(~result.success).sum()}} segments")
            return None


    if __name__ == "__main__":
        smooth_trajectory(WAYPOINTS)
    """)


# ---------------------------------------------------------------------------
# Isaac Sim
# ---------------------------------------------------------------------------

def isaac_sim_scene(
    robot_urdf: str = "~/dobot_cr10/cr10_robot.urdf",
    scene_name: str = "cr10_workspace",
    ground_plane: bool = True,
    lighting: str = "dome",
) -> str:
    """Generate an Isaac Sim Python scene script for the CR10 robot."""
    return textwrap.dedent(f"""\
    #!/usr/bin/env python3
    \"\"\"Isaac Sim scene: {scene_name}

    Loads the CR10 robot and workspace in Isaac Sim.
    Run inside the Isaac Sim Python environment:
        /workspace/isaaclab/_isaac_sim/python.sh {scene_name}.py

    Generated by skills/robotics.py
    \"\"\"

    from isaacsim import SimulationApp
    simulation_app = SimulationApp({{"headless": False}})

    import omni.isaac.core.utils.stage as stage_utils
    from omni.isaac.core import World
    from omni.isaac.core.robots import Robot
    from omni.isaac.core.utils.prims import create_prim
    from pxr import UsdPhysics, Gf

    world = World(stage_units_in_meters=1.0)
    scene = world.scene

    # Ground plane
    {"scene.add_ground_plane()" if ground_plane else "# No ground plane"}

    # Lighting
    create_prim(
        "/World/Light",
        "DomeLight" if "{lighting}" == "dome" else "DistantLight",
        attributes={{"intensity": 1000.0}},
    )

    # Load CR10 robot from URDF
    from omni.isaac.urdf import _urdf
    urdf_interface = _urdf.acquire_urdf_interface()
    import_config = _urdf.ImportConfig()
    import_config.merge_fixed_joints = False
    import_config.fix_base = True
    import_config.make_default_prim = True

    result = urdf_interface.parse_urdf("{robot_urdf}", import_config)
    urdf_interface.import_robot(
        "{robot_urdf}",
        result,
        import_config,
        "/World/CR10",
    )

    robot = scene.add(Robot(prim_path="/World/CR10", name="cr10"))

    # Physics
    world.reset()

    print(f"Scene '{scene_name}' loaded with CR10 robot")
    print(f"Robot DOF: {{robot.num_dof}}")
    print(f"Joint names: {{robot.dof_names}}")

    # Simulation loop
    while simulation_app.is_running():
        world.step(render=True)

    simulation_app.close()
    """)


# ---------------------------------------------------------------------------
# URDF
# ---------------------------------------------------------------------------

def urdf_consolidation(
    source_urdfs: list[str] | None = None,
    output_name: str = "cr10_canonical",
) -> str:
    """Generate a script to consolidate multiple URDF files into one canonical version."""
    if source_urdfs is None:
        source_urdfs = [
            "~/dobot_cr10/cr10_robot.urdf",
            "~/dobot-cr10-stack/ros2/dobot_cr10_driver/urdf/dobot_cr10.urdf",
            "~/dobot_cr10/urdf/dobot_cr10.urdf",
        ]
    sources_str = ",\n        ".join(f'"{s}"' for s in source_urdfs)
    return textwrap.dedent(f"""\
    #!/usr/bin/env python3
    \"\"\"URDF consolidation script for CR10.

    Reads multiple URDF sources, compares joint limits, inertials, and meshes,
    then produces a canonical URDF combining the best from each.

    Generated by skills/robotics.py
    \"\"\"

    import os
    import xml.etree.ElementTree as ET
    from dataclasses import dataclass

    SOURCES = [
        {sources_str}
    ]
    OUTPUT = os.path.expanduser("~/dobot_cr10/{output_name}.urdf")


    @dataclass
    class JointInfo:
        name: str
        type: str
        lower: float
        upper: float
        velocity: float
        effort: float
        source: str


    def parse_joints(urdf_path: str) -> list[JointInfo]:
        tree = ET.parse(os.path.expanduser(urdf_path))
        root = tree.getroot()
        joints = []
        for j in root.findall("joint"):
            limit = j.find("limit")
            if limit is None:
                continue
            joints.append(JointInfo(
                name=j.get("name"),
                type=j.get("type"),
                lower=float(limit.get("lower", 0)),
                upper=float(limit.get("upper", 0)),
                velocity=float(limit.get("velocity", 0)),
                effort=float(limit.get("effort", 0)),
                source=urdf_path,
            ))
        return joints


    def compare_sources():
        print("# URDF Comparison Report")
        for path in SOURCES:
            expanded = os.path.expanduser(path)
            if not os.path.exists(expanded):
                print(f"  MISSING: {{path}}")
                continue
            joints = parse_joints(path)
            print(f"\\n## {{path}}")
            for j in joints:
                print(f"  {{j.name}} ({{j.type}}): "
                      f"[{{j.lower:.4f}}, {{j.upper:.4f}}] "
                      f"vel={{j.velocity}} effort={{j.effort}}")


    if __name__ == "__main__":
        compare_sources()
    """)


# ---------------------------------------------------------------------------
# ROS2
# ---------------------------------------------------------------------------

def ros2_launch(
    package: str = "dobot_cr10_driver",
    node_name: str = "cr10_driver",
    robot_ip: str = "192.168.5.1",
    use_sim: bool = False,
) -> str:
    """Generate a ROS2 launch file for the CR10 driver or simulation bridge."""
    sim_param = "true" if use_sim else "false"
    return textwrap.dedent(f"""\
    # ROS2 launch file for {package}
    # Generated by skills/robotics.py

    from launch import LaunchDescription
    from launch.actions import DeclareLaunchArgument
    from launch.substitutions import LaunchConfiguration
    from launch_ros.actions import Node


    def generate_launch_description():
        return LaunchDescription([
            DeclareLaunchArgument("robot_ip", default_value="{robot_ip}"),
            DeclareLaunchArgument("use_sim", default_value="{sim_param}"),

            Node(
                package="{package}",
                executable="{node_name}",
                name="{node_name}",
                parameters=[{{
                    "robot_ip": LaunchConfiguration("robot_ip"),
                    "use_sim": LaunchConfiguration("use_sim"),
                    "dashboard_port": 29999,
                    "control_port": 30003,
                    "feedback_port": 30004,
                    "publish_rate": 100.0,
                }}],
                output="screen",
            ),
        ])
    """)
