"""Safety skills — test suite generators for robot safety validation.

Each skill generates a Python test script that validates a specific
safety aspect of the CR10 robot system.
"""

import textwrap


def workspace_test(
    joint_limits: dict[str, tuple[float, float]] | None = None,
    max_reach: float = 1.525,
) -> str:
    """Generate a workspace boundary validation test for the CR10."""
    if joint_limits is None:
        joint_limits = {
            "joint1": (-3.14, 3.14),
            "joint2": (-3.14, 3.14),
            "joint3": (-2.861, 2.861),
            "joint4": (-3.14, 3.14),
            "joint5": (-3.14, 3.14),
            "joint6": (-6.28, 6.28),
        }
    limits_str = ",\n    ".join(
        f'"{k}": ({v[0]}, {v[1]})' for k, v in joint_limits.items()
    )
    return textwrap.dedent(f"""\
    #!/usr/bin/env python3
    \"\"\"Workspace boundary validation test for Dobot CR10.

    Verifies that commanded joint positions stay within hardware limits
    and that the end-effector stays within the max reach envelope.

    Generated by skills/safety.py
    \"\"\"

    import numpy as np

    JOINT_LIMITS = {{
        {limits_str}
    }}
    MAX_REACH = {max_reach}  # meters


    def test_joint_limits(positions: dict[str, float]) -> list[str]:
        \"\"\"Check if joint positions are within limits.\"\"\"
        violations = []
        for joint, pos in positions.items():
            if joint not in JOINT_LIMITS:
                violations.append(f"Unknown joint: {{joint}}")
                continue
            lo, hi = JOINT_LIMITS[joint]
            if pos < lo or pos > hi:
                violations.append(
                    f"{{joint}}: {{pos:.4f}} out of range [{lo}, {hi}]"
                )
        return violations


    def test_reach(ee_position: np.ndarray) -> bool:
        \"\"\"Check if end-effector position is within reach envelope.\"\"\"
        distance = np.linalg.norm(ee_position[:2])  # XY distance from base
        return distance <= MAX_REACH


    def run_tests():
        print("# Workspace Boundary Tests")

        # Test 1: Valid positions
        valid = {{"joint1": 0.0, "joint2": -1.57, "joint3": 1.57,
                 "joint4": 0.0, "joint5": 1.57, "joint6": 0.0}}
        v = test_joint_limits(valid)
        print(f"  Valid positions: {{'PASS' if not v else 'FAIL: ' + str(v)}}")

        # Test 2: Out-of-range position
        invalid = {{"joint3": 3.5}}  # exceeds 2.861 limit
        v = test_joint_limits(invalid)
        print(f"  Out-of-range detection: {{'PASS' if v else 'FAIL'}}")

        # Test 3: Reach envelope
        inside = np.array([1.0, 0.5, 0.3])
        outside = np.array([2.0, 0.0, 0.0])
        r1 = test_reach(inside)
        r2 = test_reach(outside)
        print(f"  Inside reach: {{'PASS' if r1 else 'FAIL'}}")
        print(f"  Outside reach: {{'PASS' if not r2 else 'FAIL'}}")


    if __name__ == "__main__":
        run_tests()
    """)


def velocity_test(
    max_joint_velocities: list[float] | None = None,
    max_tcp_velocity: float = 1.0,
) -> str:
    """Generate a velocity limit validation test for the CR10."""
    if max_joint_velocities is None:
        max_joint_velocities = [2.094, 2.094, 3.0, 3.927, 3.927, 6.283]
    vel_str = str(max_joint_velocities)
    return textwrap.dedent(f"""\
    #!/usr/bin/env python3
    \"\"\"Velocity limit validation test for Dobot CR10.

    Verifies joint velocities and TCP velocity stay within safe limits.

    Generated by skills/safety.py
    \"\"\"

    import numpy as np

    MAX_JOINT_VELOCITIES = {vel_str}  # rad/s per joint
    MAX_TCP_VELOCITY = {max_tcp_velocity}  # m/s


    def test_joint_velocities(velocities: list[float]) -> list[str]:
        violations = []
        for i, (vel, limit) in enumerate(zip(velocities, MAX_JOINT_VELOCITIES)):
            if abs(vel) > limit:
                violations.append(
                    f"joint{{i+1}}: {{abs(vel):.3f}} > {{limit}} rad/s"
                )
        return violations


    def test_tcp_velocity(tcp_vel: np.ndarray) -> bool:
        speed = np.linalg.norm(tcp_vel)
        return speed <= MAX_TCP_VELOCITY


    def run_tests():
        print("# Velocity Limit Tests")
        safe = [1.0, 1.0, 2.0, 2.0, 2.0, 3.0]
        v = test_joint_velocities(safe)
        print(f"  Safe velocities: {{'PASS' if not v else 'FAIL: ' + str(v)}}")

        unsafe = [3.0, 1.0, 1.0, 5.0, 1.0, 1.0]
        v = test_joint_velocities(unsafe)
        print(f"  Unsafe detection: {{'PASS' if v else 'FAIL'}}")

        tcp_safe = np.array([0.3, 0.4, 0.1])
        tcp_fast = np.array([0.8, 0.8, 0.2])
        print(f"  TCP safe: {{'PASS' if test_tcp_velocity(tcp_safe) else 'FAIL'}}")
        print(f"  TCP too fast: {{'PASS' if not test_tcp_velocity(tcp_fast) else 'FAIL'}}")


    if __name__ == "__main__":
        run_tests()
    """)


def payload_test(
    max_payload: float = 10.0,
    max_moment: float = 30.0,
) -> str:
    """Generate a payload validation test for the CR10 (10kg max)."""
    return textwrap.dedent(f"""\
    #!/usr/bin/env python3
    \"\"\"Payload validation test for Dobot CR10.

    Verifies payload mass and moment are within robot specifications.
    CR10 max payload: {max_payload}kg, max moment: {max_moment}Nm.

    Generated by skills/safety.py
    \"\"\"

    MAX_PAYLOAD = {max_payload}  # kg
    MAX_MOMENT = {max_moment}  # Nm


    def test_payload(mass: float, cog_offset: float = 0.0) -> dict:
        moment = mass * 9.81 * cog_offset
        return {{
            "mass_ok": mass <= MAX_PAYLOAD,
            "moment_ok": abs(moment) <= MAX_MOMENT,
            "mass": mass,
            "moment": moment,
            "mass_margin": MAX_PAYLOAD - mass,
            "moment_margin": MAX_MOMENT - abs(moment),
        }}


    def run_tests():
        print("# Payload Tests")

        # ARRI Alexa Mini (~2.3kg body + lens ~1.5kg + accessories)
        alexa = test_payload(mass=5.0, cog_offset=0.15)
        print(f"  Alexa Mini (5kg, 15cm offset): "
              f"{{'PASS' if alexa['mass_ok'] and alexa['moment_ok'] else 'FAIL'}}")
        print(f"    Mass margin: {{alexa['mass_margin']:.1f}}kg")
        print(f"    Moment: {{alexa['moment']:.2f}}Nm (margin: {{alexa['moment_margin']:.1f}}Nm)")

        # Overweight
        heavy = test_payload(mass=12.0, cog_offset=0.1)
        print(f"  Overweight (12kg): {{'PASS' if not heavy['mass_ok'] else 'FAIL'}}")


    if __name__ == "__main__":
        run_tests()
    """)


def estop_test() -> str:
    """Generate an E-stop validation test script for the CR10 safety system."""
    return textwrap.dedent("""\
    #!/usr/bin/env python3
    \"\"\"E-stop validation test for Dobot CR10.

    Tests the software E-stop mechanism:
    1. E-stop triggers immediately on command
    2. Robot stops within safe deceleration limits
    3. E-stop state persists until explicitly cleared
    4. Robot requires re-enable sequence after E-stop

    Generated by skills/safety.py
    \"\"\"

    import time
    import socket


    class EStopTest:
        def __init__(self, robot_ip: str = "192.168.5.1"):
            self.robot_ip = robot_ip
            self.dashboard_port = 29999

        def send_dashboard(self, command: str) -> str:
            try:
                sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
                sock.settimeout(3)
                sock.connect((self.robot_ip, self.dashboard_port))
                sock.recv(1024)  # banner
                sock.sendall(f"{command}\\n".encode())
                response = sock.recv(1024).decode().strip()
                sock.close()
                return response
            except Exception as e:
                return f"ERROR: {e}"

        def test_estop_trigger(self) -> bool:
            response = self.send_dashboard("EmergencyStop()")
            return "0" in response  # 0 = success

        def test_robot_mode_after_estop(self) -> bool:
            response = self.send_dashboard("RobotMode()")
            # Mode 4 = emergency stopped
            return "4" in response

        def test_clear_and_reenable(self) -> bool:
            self.send_dashboard("ClearError()")
            self.send_dashboard("EnableRobot()")
            time.sleep(2)
            response = self.send_dashboard("RobotMode()")
            # Mode 5 = enabled/idle
            return "5" in response

        def run_all(self):
            print("# E-Stop Tests")
            print(f"  Trigger: {'PASS' if self.test_estop_trigger() else 'FAIL'}")
            time.sleep(1)
            print(f"  Mode check: {'PASS' if self.test_robot_mode_after_estop() else 'FAIL'}")
            print(f"  Re-enable: {'PASS' if self.test_clear_and_reenable() else 'FAIL'}")


    if __name__ == "__main__":
        test = EStopTest()
        test.run_all()
    """)


def human_proximity_test(
    min_distance: float = 0.5,
    slowdown_distance: float = 1.5,
) -> str:
    """Generate a human proximity safety test using NvBlox distance fields."""
    return textwrap.dedent(f"""\
    #!/usr/bin/env python3
    \"\"\"Human proximity safety test using NvBlox.

    Tests the safety system's ability to detect humans and adjust robot behavior:
    - Stop zone: < {min_distance}m → immediate stop
    - Slowdown zone: < {slowdown_distance}m → reduce speed
    - Normal zone: >= {slowdown_distance}m → full speed

    NvBlox feeds the SAFETY SYSTEM (not cuRobo).

    Generated by skills/safety.py
    \"\"\"

    MIN_DISTANCE = {min_distance}  # meters — immediate stop
    SLOWDOWN_DISTANCE = {slowdown_distance}  # meters — reduce speed


    def classify_distance(distance: float) -> str:
        if distance < MIN_DISTANCE:
            return "STOP"
        elif distance < SLOWDOWN_DISTANCE:
            return "SLOW"
        else:
            return "NORMAL"


    def speed_factor(distance: float) -> float:
        if distance < MIN_DISTANCE:
            return 0.0
        elif distance < SLOWDOWN_DISTANCE:
            # Linear ramp from 0 to 1
            return (distance - MIN_DISTANCE) / (SLOWDOWN_DISTANCE - MIN_DISTANCE)
        else:
            return 1.0


    def run_tests():
        print("# Human Proximity Tests")
        test_cases = [
            (0.3, "STOP"),
            (0.5, "SLOW"),
            (1.0, "SLOW"),
            (1.5, "NORMAL"),
            (3.0, "NORMAL"),
        ]
        for dist, expected in test_cases:
            result = classify_distance(dist)
            status = "PASS" if result == expected else "FAIL"
            factor = speed_factor(dist)
            print(f"  {{dist}}m: {{result}} (speed={{factor:.0%}}) — {{status}}")


    if __name__ == "__main__":
        run_tests()
    """)


def safety_report() -> str:
    """Generate a comprehensive safety validation report template."""
    return textwrap.dedent("""\
    #!/usr/bin/env python3
    \"\"\"Comprehensive safety validation report for Dobot CR10.

    Runs all safety tests and generates a summary report.

    Generated by skills/safety.py
    \"\"\"

    import datetime


    def generate_report(results: dict[str, dict]) -> str:
        lines = [
            "# CR10 Safety Validation Report",
            f"Date: {datetime.datetime.now().isoformat()}",
            f"Robot: Dobot CR10 (10kg payload, 1525mm reach)",
            "",
        ]

        total = 0
        passed = 0
        for category, tests in results.items():
            lines.append(f"## {category}")
            for name, result in tests.items():
                total += 1
                status = "PASS" if result["pass"] else "FAIL"
                if result["pass"]:
                    passed += 1
                lines.append(f"  [{status}] {name}: {result.get('detail', '')}")
            lines.append("")

        lines.append(f"## Summary: {passed}/{total} tests passed")
        if passed == total:
            lines.append("Status: ALL TESTS PASSED")
        else:
            lines.append(f"Status: {total - passed} FAILURES — DO NOT DEPLOY")

        return "\\n".join(lines)


    if __name__ == "__main__":
        # Example with placeholder results
        results = {
            "Workspace": {
                "Joint limits": {"pass": True, "detail": "All joints within range"},
                "Reach envelope": {"pass": True, "detail": "EE within 1525mm"},
            },
            "Velocity": {
                "Joint velocity": {"pass": True, "detail": "All joints < max"},
                "TCP velocity": {"pass": True, "detail": "< 1.0 m/s"},
            },
            "Payload": {
                "Mass check": {"pass": True, "detail": "5.0kg < 10.0kg"},
                "Moment check": {"pass": True, "detail": "7.36Nm < 30.0Nm"},
            },
            "E-Stop": {
                "Trigger": {"pass": False, "detail": "Robot not connected"},
            },
            "Proximity": {
                "Stop zone": {"pass": True, "detail": "Stops at 0.3m"},
                "Slow zone": {"pass": True, "detail": "Slows at 1.0m"},
            },
        }
        print(generate_report(results))
    """)
