"""Safety skills — test suite generators for robot safety validation.

Each skill generates a Python test script that validates a specific
safety aspect of the CR10 robot system.
"""

import textwrap


def workspace_test(
    joint_limits: dict[str, tuple[float, float]] | None = None,
    max_reach: float = 1.525,
) -> str:
    """Generate a workspace boundary validation test for the CR10."""
    if joint_limits is None:
        joint_limits = {
            "joint1": (-3.14, 3.14),
            "joint2": (-3.14, 3.14),
            "joint3": (-2.861, 2.861),
            "joint4": (-3.14, 3.14),
            "joint5": (-3.14, 3.14),
            "joint6": (-6.28, 6.28),
        }
    limits_str = ",\n    ".join(
        f'"{k}": ({v[0]}, {v[1]})' for k, v in joint_limits.items()
    )
    return textwrap.dedent(f"""\
    #!/usr/bin/env python3
    \"\"\"Workspace boundary validation test for Dobot CR10.

    Verifies that commanded joint positions stay within hardware limits
    and that the end-effector stays within the max reach envelope.

    Generated by skills/safety.py
    \"\"\"

    import numpy as np

    JOINT_LIMITS = {{
        {limits_str}
    }}
    MAX_REACH = {max_reach}  # meters


    def test_joint_limits(positions: dict[str, float]) -> list[str]:
        \"\"\"Check if joint positions are within limits.\"\"\"
        violations = []
        for joint, pos in positions.items():
            if joint not in JOINT_LIMITS:
                violations.append(f"Unknown joint: {{joint}}")
                continue
            lo, hi = JOINT_LIMITS[joint]
            if pos < lo or pos > hi:
                violations.append(
                    f"{{joint}}: {{pos:.4f}} out of range [{lo}, {hi}]"
                )
        return violations


    def test_reach(ee_position: np.ndarray) -> bool:
        \"\"\"Check if end-effector position is within reach envelope.\"\"\"
        distance = np.linalg.norm(ee_position[:2])  # XY distance from base
        return distance <= MAX_REACH


    def run_tests():
        print("# Workspace Boundary Tests")

        # Test 1: Valid positions
        valid = {{"joint1": 0.0, "joint2": -1.57, "joint3": 1.57,
                 "joint4": 0.0, "joint5": 1.57, "joint6": 0.0}}
        v = test_joint_limits(valid)
        print(f"  Valid positions: {{'PASS' if not v else 'FAIL: ' + str(v)}}")

        # Test 2: Out-of-range position
        invalid = {{"joint3": 3.5}}  # exceeds 2.861 limit
        v = test_joint_limits(invalid)
        print(f"  Out-of-range detection: {{'PASS' if v else 'FAIL'}}")

        # Test 3: Reach envelope
        inside = np.array([1.0, 0.5, 0.3])
        outside = np.array([2.0, 0.0, 0.0])
        r1 = test_reach(inside)
        r2 = test_reach(outside)
        print(f"  Inside reach: {{'PASS' if r1 else 'FAIL'}}")
        print(f"  Outside reach: {{'PASS' if not r2 else 'FAIL'}}")


    if __name__ == "__main__":
        run_tests()
    """)


def velocity_test(
    max_joint_velocities: list[float] | None = None,
    max_tcp_velocity: float = 1.0,
) -> str:
    """Generate a velocity limit validation test for the CR10."""
    if max_joint_velocities is None:
        max_joint_velocities = [2.094, 2.094, 3.0, 3.927, 3.927, 6.283]
    vel_str = str(max_joint_velocities)
    return textwrap.dedent(f"""\
    #!/usr/bin/env python3
    \"\"\"Velocity limit validation test for Dobot CR10.

    Verifies joint velocities and TCP velocity stay within safe limits.

    Generated by skills/safety.py
    \"\"\"

    import numpy as np

    MAX_JOINT_VELOCITIES = {vel_str}  # rad/s per joint
    MAX_TCP_VELOCITY = {max_tcp_velocity}  # m/s


    def test_joint_velocities(velocities: list[float]) -> list[str]:
        violations = []
        for i, (vel, limit) in enumerate(zip(velocities, MAX_JOINT_VELOCITIES)):
            if abs(vel) > limit:
                violations.append(
                    f"joint{{i+1}}: {{abs(vel):.3f}} > {{limit}} rad/s"
                )
        return violations


    def test_tcp_velocity(tcp_vel: np.ndarray) -> bool:
        speed = np.linalg.norm(tcp_vel)
        return speed <= MAX_TCP_VELOCITY


    def run_tests():
        print("# Velocity Limit Tests")
        safe = [1.0, 1.0, 2.0, 2.0, 2.0, 3.0]
        v = test_joint_velocities(safe)
        print(f"  Safe velocities: {{'PASS' if not v else 'FAIL: ' + str(v)}}")

        unsafe = [3.0, 1.0, 1.0, 5.0, 1.0, 1.0]
        v = test_joint_velocities(unsafe)
        print(f"  Unsafe detection: {{'PASS' if v else 'FAIL'}}")

        tcp_safe = np.array([0.3, 0.4, 0.1])
        tcp_fast = np.array([0.8, 0.8, 0.2])
        print(f"  TCP safe: {{'PASS' if test_tcp_velocity(tcp_safe) else 'FAIL'}}")
        print(f"  TCP too fast: {{'PASS' if not test_tcp_velocity(tcp_fast) else 'FAIL'}}")


    if __name__ == "__main__":
        run_tests()
    """)


def payload_test(
    max_payload: float = 10.0,
    max_moment: float = 30.0,
) -> str:
    """Generate a payload validation test for the CR10 (10kg max)."""
    return textwrap.dedent(f"""\
    #!/usr/bin/env python3
    \"\"\"Payload validation test for Dobot CR10.

    Verifies payload mass and moment are within robot specifications.
    CR10 max payload: {max_payload}kg, max moment: {max_moment}Nm.

    Generated by skills/safety.py
    \"\"\"

    MAX_PAYLOAD = {max_payload}  # kg
    MAX_MOMENT = {max_moment}  # Nm


    def test_payload(mass: float, cog_offset: float = 0.0) -> dict:
        moment = mass * 9.81 * cog_offset
        return {{
            "mass_ok": mass <= MAX_PAYLOAD,
            "moment_ok": abs(moment) <= MAX_MOMENT,
            "mass": mass,
            "moment": moment,
            "mass_margin": MAX_PAYLOAD - mass,
            "moment_margin": MAX_MOMENT - abs(moment),
        }}


    def run_tests():
        print("# Payload Tests")

        # ARRI Alexa Mini (~2.3kg body + lens ~1.5kg + accessories)
        alexa = test_payload(mass=5.0, cog_offset=0.15)
        print(f"  Alexa Mini (5kg, 15cm offset): "
              f"{{'PASS' if alexa['mass_ok'] and alexa['moment_ok'] else 'FAIL'}}")
        print(f"    Mass margin: {{alexa['mass_margin']:.1f}}kg")
        print(f"    Moment: {{alexa['moment']:.2f}}Nm (margin: {{alexa['moment_margin']:.1f}}Nm)")

        # Overweight
        heavy = test_payload(mass=12.0, cog_offset=0.1)
        print(f"  Overweight (12kg): {{'PASS' if not heavy['mass_ok'] else 'FAIL'}}")


    if __name__ == "__main__":
        run_tests()
    """)


def estop_test() -> str:
    """Generate an E-stop validation test script for the CR10 safety system."""
    return textwrap.dedent("""\
    #!/usr/bin/env python3
    \"\"\"E-stop validation test for Dobot CR10.

    Tests the software E-stop mechanism:
    1. E-stop triggers immediately on command
    2. Robot stops within safe deceleration limits
    3. E-stop state persists until explicitly cleared
    4. Robot requires re-enable sequence after E-stop

    Generated by skills/safety.py
    \"\"\"

    import time
    import socket


    class EStopTest:
        def __init__(self, robot_ip: str = "192.168.5.1"):
            self.robot_ip = robot_ip
            self.dashboard_port = 29999

        def send_dashboard(self, command: str) -> str:
            try:
                sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
                sock.settimeout(3)
                sock.connect((self.robot_ip, self.dashboard_port))
                sock.recv(1024)  # banner
                sock.sendall(f"{command}\\n".encode())
                response = sock.recv(1024).decode().strip()
                sock.close()
                return response
            except Exception as e:
                return f"ERROR: {e}"

        def test_estop_trigger(self) -> bool:
            response = self.send_dashboard("EmergencyStop()")
            return "0" in response  # 0 = success

        def test_robot_mode_after_estop(self) -> bool:
            response = self.send_dashboard("RobotMode()")
            # Mode 4 = emergency stopped
            return "4" in response

        def test_clear_and_reenable(self) -> bool:
            self.send_dashboard("ClearError()")
            self.send_dashboard("EnableRobot()")
            time.sleep(2)
            response = self.send_dashboard("RobotMode()")
            # Mode 5 = enabled/idle
            return "5" in response

        def run_all(self):
            print("# E-Stop Tests")
            print(f"  Trigger: {'PASS' if self.test_estop_trigger() else 'FAIL'}")
            time.sleep(1)
            print(f"  Mode check: {'PASS' if self.test_robot_mode_after_estop() else 'FAIL'}")
            print(f"  Re-enable: {'PASS' if self.test_clear_and_reenable() else 'FAIL'}")


    if __name__ == "__main__":
        test = EStopTest()
        test.run_all()
    """)


def human_proximity_test(
    min_distance: float = 0.5,
    slowdown_distance: float = 1.5,
) -> str:
    """Generate a human proximity safety test using NvBlox distance fields."""
    return textwrap.dedent(f"""\
    #!/usr/bin/env python3
    \"\"\"Human proximity safety test using NvBlox.

    Tests the safety system's ability to detect humans and adjust robot behavior:
    - Stop zone: < {min_distance}m → immediate stop
    - Slowdown zone: < {slowdown_distance}m → reduce speed
    - Normal zone: >= {slowdown_distance}m → full speed

    NvBlox feeds the SAFETY SYSTEM (not cuRobo).

    Generated by skills/safety.py
    \"\"\"

    MIN_DISTANCE = {min_distance}  # meters — immediate stop
    SLOWDOWN_DISTANCE = {slowdown_distance}  # meters — reduce speed


    def classify_distance(distance: float) -> str:
        if distance < MIN_DISTANCE:
            return "STOP"
        elif distance < SLOWDOWN_DISTANCE:
            return "SLOW"
        else:
            return "NORMAL"


    def speed_factor(distance: float) -> float:
        if distance < MIN_DISTANCE:
            return 0.0
        elif distance < SLOWDOWN_DISTANCE:
            # Linear ramp from 0 to 1
            return (distance - MIN_DISTANCE) / (SLOWDOWN_DISTANCE - MIN_DISTANCE)
        else:
            return 1.0


    def run_tests():
        print("# Human Proximity Tests")
        test_cases = [
            (0.3, "STOP"),
            (0.5, "SLOW"),
            (1.0, "SLOW"),
            (1.5, "NORMAL"),
            (3.0, "NORMAL"),
        ]
        for dist, expected in test_cases:
            result = classify_distance(dist)
            status = "PASS" if result == expected else "FAIL"
            factor = speed_factor(dist)
            print(f"  {{dist}}m: {{result}} (speed={{factor:.0%}}) — {{status}}")


    if __name__ == "__main__":
        run_tests()
    """)


def safety_report() -> str:
    """Generate a comprehensive safety validation report template."""
    return textwrap.dedent("""\
    #!/usr/bin/env python3
    \"\"\"Comprehensive safety validation report for Dobot CR10.

    Runs all safety tests and generates a summary report.

    Generated by skills/safety.py
    \"\"\"

    import datetime


    def generate_report(results: dict[str, dict]) -> str:
        lines = [
            "# CR10 Safety Validation Report",
            f"Date: {datetime.datetime.now().isoformat()}",
            f"Robot: Dobot CR10 (10kg payload, 1525mm reach)",
            "",
        ]

        total = 0
        passed = 0
        for category, tests in results.items():
            lines.append(f"## {category}")
            for name, result in tests.items():
                total += 1
                status = "PASS" if result["pass"] else "FAIL"
                if result["pass"]:
                    passed += 1
                lines.append(f"  [{status}] {name}: {result.get('detail', '')}")
            lines.append("")

        lines.append(f"## Summary: {passed}/{total} tests passed")
        if passed == total:
            lines.append("Status: ALL TESTS PASSED")
        else:
            lines.append(f"Status: {total - passed} FAILURES — DO NOT DEPLOY")

        return "\\n".join(lines)


    if __name__ == "__main__":
        # Example with placeholder results
        results = {
            "Workspace": {
                "Joint limits": {"pass": True, "detail": "All joints within range"},
                "Reach envelope": {"pass": True, "detail": "EE within 1525mm"},
            },
            "Velocity": {
                "Joint velocity": {"pass": True, "detail": "All joints < max"},
                "TCP velocity": {"pass": True, "detail": "< 1.0 m/s"},
            },
            "Payload": {
                "Mass check": {"pass": True, "detail": "5.0kg < 10.0kg"},
                "Moment check": {"pass": True, "detail": "7.36Nm < 30.0Nm"},
            },
            "E-Stop": {
                "Trigger": {"pass": False, "detail": "Robot not connected"},
            },
            "Proximity": {
                "Stop zone": {"pass": True, "detail": "Stops at 0.3m"},
                "Slow zone": {"pass": True, "detail": "Slows at 1.0m"},
            },
        }
        print(generate_report(results))
    """)


def safety_monitor_node() -> str:
    """Generate the ROS2 safety monitor node skeleton for CR10."""
    return textwrap.dedent("""\
    #!/usr/bin/env python3
    \"\"\"Safety Monitor Node — queries NvBlox ESDF and classifies safety zones.

    Subscribes to:
      /nvblox/human_esdf_pointcloud (PointCloud2) — human distance field
      /joint_states (JointState) — current robot state

    Publishes:
      /safety/state (SafetyState) — zone, speed_factor, distances
      /safety/heartbeat (Header) — monitor alive signal

    Pipeline position: NvBlox → THIS → Safety Enforcer
    Generated by skills/safety.py
    \"\"\"

    import rclpy
    from rclpy.node import Node
    from std_msgs.msg import Header
    from sensor_msgs.msg import JointState, PointCloud2
    import numpy as np
    import yaml
    import os
    import time


    class SafetyMonitorNode(Node):
        def __init__(self):
            super().__init__('safety_monitor')

            # Load zone config
            config_path = os.path.expanduser('~/dobot_cr10/config/safety/safety_zones.yaml')
            with open(config_path) as f:
                self.config = yaml.safe_load(f)['safety_zones']

            self.zones = {
                'estop': self.config['estop_distance_m'],
                'stop': self.config['stop_distance_m'],
                'warning': self.config['warning_distance_m'],
            }

            # State
            self.current_zone = 'NORMAL'
            self.speed_factor = 1.0
            self.min_human_distance = float('inf')
            self.last_esdf_time = time.time()
            self.last_joint_state = None
            self.perception_healthy = False

            # Subscribers
            self.create_subscription(
                PointCloud2, '/nvblox/human_esdf_pointcloud',
                self.esdf_callback, 10)
            self.create_subscription(
                JointState, '/joint_states',
                self.joint_callback, 10)

            # Publishers
            # TODO: Replace Header with custom SafetyState message
            self.safety_pub = self.create_publisher(Header, '/safety/state', 10)
            self.heartbeat_pub = self.create_publisher(Header, '/safety/heartbeat', 10)

            # Timer: 50Hz safety loop
            self.create_timer(0.02, self.safety_loop)
            # Timer: 10Hz heartbeat
            self.create_timer(0.1, self.publish_heartbeat)

            self.get_logger().info('Safety Monitor initialized')

        def esdf_callback(self, msg):
            self.last_esdf_time = time.time()
            self.perception_healthy = True
            # TODO: Extract minimum distance to human from ESDF pointcloud
            # For now, placeholder
            self.min_human_distance = float('inf')

        def joint_callback(self, msg):
            self.last_joint_state = msg

        def classify_zone(self, distance: float) -> tuple:
            \"\"\"Classify distance into safety zone and compute speed factor.\"\"\"
            if distance < self.zones['estop']:
                return 'ESTOP', 0.0
            elif distance < self.zones['stop']:
                return 'STOP', 0.0
            elif distance < self.zones['warning']:
                # Linear ramp from 0 to 1
                factor = (distance - self.zones['stop']) / (
                    self.zones['warning'] - self.zones['stop'])
                return 'WARNING', max(0.0, min(1.0, factor))
            else:
                return 'NORMAL', 1.0

        def safety_loop(self):
            now = time.time()

            # Watchdog: check perception freshness
            esdf_age_ms = (now - self.last_esdf_time) * 1000
            heartbeat_timeout = self.config['heartbeat_timeout_ms']
            sensor_timeout = self.config['sensor_timeout_ms']

            if esdf_age_ms > heartbeat_timeout:
                self.current_zone = 'ESTOP'
                self.speed_factor = 0.0
                self.perception_healthy = False
            elif esdf_age_ms > sensor_timeout:
                self.current_zone = 'STOP'
                self.speed_factor = 0.0
                self.perception_healthy = False
            else:
                self.current_zone, self.speed_factor = self.classify_zone(
                    self.min_human_distance)

            # Publish safety state
            msg = Header()
            msg.stamp = self.get_clock().now().to_msg()
            msg.frame_id = f'{self.current_zone}|{self.speed_factor:.2f}|{self.min_human_distance:.2f}'
            self.safety_pub.publish(msg)

        def publish_heartbeat(self):
            msg = Header()
            msg.stamp = self.get_clock().now().to_msg()
            msg.frame_id = 'safety_monitor_alive'
            self.heartbeat_pub.publish(msg)


    def main(args=None):
        rclpy.init(args=args)
        node = SafetyMonitorNode()
        try:
            rclpy.spin(node)
        except KeyboardInterrupt:
            pass
        finally:
            node.destroy_node()
            rclpy.shutdown()


    if __name__ == '__main__':
        main()
    """)


def safety_enforcer_node() -> str:
    """Generate the ROS2 safety enforcer node skeleton for CR10."""
    return textwrap.dedent("""\
    #!/usr/bin/env python3
    \"\"\"Safety Enforcer Node — gates trajectory commands based on safety state.

    Subscribes to:
      /safety/state (Header) — zone and speed factor from safety monitor
      /joint_trajectory (JointTrajectory) — commands from cinema pipeline
      /safety/heartbeat (Header) — monitor alive signal

    Publishes:
      /joint_command (JointTrajectory) — validated, speed-limited commands to driver

    This is the LAST gate before the robot driver.
    Generated by skills/safety.py
    \"\"\"

    import rclpy
    from rclpy.node import Node
    from std_msgs.msg import Header
    from trajectory_msgs.msg import JointTrajectory, JointTrajectoryPoint
    import time
    import yaml
    import os


    class SafetyState:
        NORMAL = 'NORMAL'
        WARNING = 'WARNING'
        STOP = 'STOP'
        ESTOP = 'ESTOP'
        RECOVERY = 'RECOVERY'
        SENSOR_FAULT = 'SENSOR_FAULT'


    class SafetyEnforcerNode(Node):
        def __init__(self):
            super().__init__('safety_enforcer')

            config_path = os.path.expanduser('~/dobot_cr10/config/safety/safety_zones.yaml')
            with open(config_path) as f:
                self.config = yaml.safe_load(f)['safety_zones']

            # State machine
            self.state = SafetyState.STOP  # Start stopped until perception confirms clear
            self.speed_factor = 0.0
            self.estop_active = False
            self.last_monitor_heartbeat = 0.0
            self.normal_start_time = None  # For recovery hold timer

            # URDF velocity limits
            self.max_joint_velocities = [2.094, 2.094, 3.0, 3.927, 3.927, 6.283]

            # Subscribers
            self.create_subscription(
                Header, '/safety/state', self.safety_state_callback, 10)
            self.create_subscription(
                Header, '/safety/heartbeat', self.heartbeat_callback, 10)
            self.create_subscription(
                JointTrajectory, '/joint_trajectory', self.trajectory_callback, 10)

            # Publisher
            self.cmd_pub = self.create_publisher(JointTrajectory, '/joint_command', 10)

            # Timer: watchdog check at 50Hz
            self.create_timer(0.02, self.watchdog)

            self.get_logger().info('Safety Enforcer initialized — state: STOP (waiting for perception)')

        def safety_state_callback(self, msg):
            parts = msg.frame_id.split('|')
            if len(parts) >= 2:
                zone = parts[0]
                factor = float(parts[1])
                self.update_state(zone, factor)

        def heartbeat_callback(self, msg):
            self.last_monitor_heartbeat = time.time()

        def update_state(self, zone: str, factor: float):
            \"\"\"State machine transitions.\"\"\"
            if self.estop_active and zone != SafetyState.ESTOP:
                # ESTOP requires manual reset — don't auto-transition
                if not self._manual_reset_received():
                    return
                self.state = SafetyState.RECOVERY
                self.speed_factor = self.config['estop']['recovery_speed_factor']
                self.get_logger().warn('ESTOP cleared — entering RECOVERY')
                return

            if zone == SafetyState.ESTOP:
                self.state = SafetyState.ESTOP
                self.speed_factor = 0.0
                self.estop_active = True
                self.get_logger().error('ESTOP ACTIVATED')
            elif zone == SafetyState.STOP:
                self.state = SafetyState.STOP
                self.speed_factor = 0.0
            elif zone == SafetyState.WARNING:
                self.state = SafetyState.WARNING
                self.speed_factor = factor
            elif zone == SafetyState.NORMAL:
                if self.state == SafetyState.RECOVERY:
                    # Must hold NORMAL for recovery_hold_time before full speed
                    if self.normal_start_time is None:
                        self.normal_start_time = time.time()
                    elapsed = time.time() - self.normal_start_time
                    if elapsed < self.config['estop']['recovery_hold_time_s']:
                        self.speed_factor = self.config['estop']['recovery_speed_factor']
                        return
                self.state = SafetyState.NORMAL
                self.speed_factor = 1.0
                self.normal_start_time = None

        def _manual_reset_received(self) -> bool:
            \"\"\"Check if manual reset was triggered. TODO: implement via service call.\"\"\"
            return False

        def trajectory_callback(self, msg):
            \"\"\"Gate and scale incoming trajectory commands.\"\"\"
            if self.state in (SafetyState.ESTOP, SafetyState.STOP, SafetyState.SENSOR_FAULT):
                self.get_logger().warn(f'Trajectory BLOCKED — state: {self.state}')
                return

            # Scale velocities by speed_factor
            scaled = JointTrajectory()
            scaled.header = msg.header
            scaled.joint_names = msg.joint_names

            for point in msg.points:
                sp = JointTrajectoryPoint()
                sp.positions = list(point.positions)
                sp.velocities = [
                    min(v * self.speed_factor, self.max_joint_velocities[i])
                    for i, v in enumerate(point.velocities)
                ] if point.velocities else []
                sp.time_from_start = point.time_from_start
                scaled.points.append(sp)

            self.cmd_pub.publish(scaled)

        def watchdog(self):
            \"\"\"Check safety monitor heartbeat.\"\"\"
            if self.last_monitor_heartbeat == 0.0:
                return  # Haven't received first heartbeat yet

            age_ms = (time.time() - self.last_monitor_heartbeat) * 1000
            if age_ms > self.config['heartbeat_timeout_ms']:
                if self.state != SafetyState.ESTOP:
                    self.get_logger().error(
                        f'Safety monitor heartbeat lost ({age_ms:.0f}ms) — ESTOP')
                    self.state = SafetyState.ESTOP
                    self.speed_factor = 0.0
                    self.estop_active = True


    def main(args=None):
        rclpy.init(args=args)
        node = SafetyEnforcerNode()
        try:
            rclpy.spin(node)
        except KeyboardInterrupt:
            pass
        finally:
            node.destroy_node()
            rclpy.shutdown()


    if __name__ == '__main__':
        main()
    """)


def nvblox_launch_config() -> str:
    """Generate NvBlox ROS2 launch file for CR10 safety perception."""
    return textwrap.dedent("""\
    # NvBlox Safety Perception Launch Configuration
    # Launch inside Isaac ROS Docker: run_isaac_ros.sh zed
    #
    # ros2 launch nvblox_example_bringup nvblox_example.launch.py \\
    #     config_file:=~/dobot_cr10/config/safety/nvblox_safety.yaml \\
    #     mode:=people_segmentation
    #
    # Or use this launch file:
    # ros2 launch cr10_safety nvblox_safety.launch.py

    from launch import LaunchDescription
    from launch_ros.actions import Node
    import os


    def generate_launch_description():
        config_file = os.path.expanduser(
            '~/dobot_cr10/config/safety/nvblox_safety.yaml')

        return LaunchDescription([
            # NvBlox human-aware node
            Node(
                package='nvblox_ros',
                executable='nvblox_human_node',
                name='nvblox_human_node',
                parameters=[config_file],
                remappings=[
                    ('depth/image', '/zed/depth/depth_registered'),
                    ('depth/camera_info', '/zed/depth/camera_info'),
                    ('color/image', '/zed/rgb/image_rect_color'),
                    ('color/camera_info', '/zed/rgb/camera_info'),
                    ('pose', '/zed/pose'),
                    ('mask/image', '/segmentation/human_mask'),
                ],
                output='screen',
            ),
        ])
    """)
