#!/usr/bin/env python3
"""Mesh preparation pipeline for Dobot CR10 digital twin.

Processes STL files: copies visuals, generates collision meshes (AABB),
produces metadata.json. Pure stdlib — no trimesh dependency.
"""

import struct
import os
import shutil
import json
from pathlib import Path


def read_stl_binary(file_path):
    """Read a binary STL file, return flat vertex list and triangle count."""
    with open(file_path, 'rb') as f:
        f.read(80)  # header
        num_triangles = struct.unpack('<I', f.read(4))[0]
        vertices = []
        for _ in range(num_triangles):
            f.read(12)  # normal
            v1 = struct.unpack('<3f', f.read(12))
            v2 = struct.unpack('<3f', f.read(12))
            v3 = struct.unpack('<3f', f.read(12))
            f.read(2)   # attribute
            vertices.extend(v1)
            vertices.extend(v2)
            vertices.extend(v3)
    return vertices, num_triangles


def compute_bounding_box(vertices):
    """Compute axis-aligned bounding box from flat vertex list."""
    x_min = y_min = z_min = float('inf')
    x_max = y_max = z_max = float('-inf')
    for i in range(0, len(vertices), 3):
        x, y, z = vertices[i], vertices[i + 1], vertices[i + 2]
        x_min, x_max = min(x_min, x), max(x_max, x)
        y_min, y_max = min(y_min, y), max(y_max, y)
        z_min, z_max = min(z_min, z), max(z_max, z)
    return (x_min, y_min, z_min), (x_max, y_max, z_max)


def compute_volume(vertices, num_triangles):
    """Compute mesh volume using signed tetrahedra method."""
    volume = 0.0
    for i in range(num_triangles):
        base = i * 9
        v1 = vertices[base:base + 3]
        v2 = vertices[base + 3:base + 6]
        v3 = vertices[base + 6:base + 9]
        volume += (v1[0] * (v2[1] * v3[2] - v2[2] * v3[1]) +
                   v1[1] * (v2[2] * v3[0] - v2[0] * v3[2]) +
                   v1[2] * (v2[0] * v3[1] - v2[1] * v3[0])) / 6.0
    return abs(volume)


def write_stl_binary(file_path, box_vertices, faces):
    """Write a binary STL from vertex list and face index list."""
    with open(file_path, 'wb') as f:
        header = b'Generated by mesh_pipeline.py'
        header += bytes(80 - len(header))
        f.write(header)
        num_tri = len(faces) // 3
        f.write(struct.pack('<I', num_tri))
        for i in range(num_tri):
            v1 = box_vertices[faces[i * 3]]
            v2 = box_vertices[faces[i * 3 + 1]]
            v3 = box_vertices[faces[i * 3 + 2]]
            f.write(struct.pack('<3f', 0, 0, 0))  # normal placeholder
            f.write(struct.pack('<3f', *v1))
            f.write(struct.pack('<3f', *v2))
            f.write(struct.pack('<3f', *v3))
            f.write(struct.pack('<H', 0))


def make_aabb_collision(bbox_min, bbox_max):
    """Generate AABB collision mesh (12 triangles, 8 vertices)."""
    x0, y0, z0 = bbox_min
    x1, y1, z1 = bbox_max
    verts = [
        (x0, y0, z0), (x1, y0, z0), (x1, y1, z0), (x0, y1, z0),
        (x0, y0, z1), (x1, y0, z1), (x1, y1, z1), (x0, y1, z1),
    ]
    faces = [
        0, 1, 2, 0, 2, 3,  # bottom
        4, 6, 5, 4, 7, 6,  # top
        0, 4, 5, 0, 5, 1,  # front
        2, 6, 7, 2, 7, 3,  # back
        0, 3, 7, 0, 7, 4,  # left
        1, 5, 6, 1, 6, 2,  # right
    ]
    return verts, faces


LINK_NAME_MAP = {
    'base_link.STL': 'base_link',
    'Link1.STL': 'link_1',
    'Link2.STL': 'link_2',
    'Link3.STL': 'link_3',
    'Link4.STL': 'link_4',
    'Link5.STL': 'link_5',
    'Link6.STL': 'link_6',
}


def run_pipeline(input_dir=None, output_base=None):
    """Process all CR10 STL files and generate metadata."""
    if input_dir is None:
        input_dir = Path('/home/samuel/Downloads/TCP-IP-ROS-6AXis-main/dobot_description/meshes/cr10/')
    else:
        input_dir = Path(input_dir)

    if output_base is None:
        output_base = Path('/home/samuel/dobot-cr10-stack/meshes/')
    else:
        output_base = Path(output_base)

    visual_dir = output_base / 'visual'
    collision_dir = output_base / 'collision'
    visual_dir.mkdir(parents=True, exist_ok=True)
    collision_dir.mkdir(parents=True, exist_ok=True)

    metadata = []

    for stl_name, link_name in LINK_NAME_MAP.items():
        src = input_dir / stl_name
        if not src.exists():
            print(f"  SKIP {stl_name} (not found)")
            continue

        print(f"  Processing {stl_name} -> {link_name}")
        vertices, num_tri = read_stl_binary(src)
        bbox_min, bbox_max = compute_bounding_box(vertices)
        volume = compute_volume(vertices, num_tri)

        # Copy visual mesh
        visual_path = visual_dir / stl_name
        shutil.copy2(src, visual_path)

        # Generate collision mesh (AABB)
        collision_name = f"{link_name}_collision.STL"
        collision_path = collision_dir / collision_name
        box_verts, box_faces = make_aabb_collision(bbox_min, bbox_max)
        write_stl_binary(collision_path, box_verts, box_faces)

        bbox_size = {
            "x": round(bbox_max[0] - bbox_min[0], 4),
            "y": round(bbox_max[1] - bbox_min[1], 4),
            "z": round(bbox_max[2] - bbox_min[2], 4),
        }

        # STL units are meters (confirmed by bounding box sizes)
        volume_m3 = volume  # already in m^3
        estimated_mass_kg = volume_m3 * 2700  # aluminum density

        metadata.append({
            "link_name": link_name,
            "visual_path": f"visual/{stl_name}",
            "collision_path": f"collision/{collision_name}",
            "visual_face_count": num_tri,
            "collision_face_count": 12,
            "bounding_box": bbox_size,
            "volume_m3": round(volume_m3, 6),
            "estimated_mass_kg": round(estimated_mass_kg, 3),
        })

        print(f"    faces={num_tri}, bbox={bbox_size}, vol={volume_m3:.6f}m³, mass={estimated_mass_kg:.3f}kg")

    meta_path = output_base / 'metadata.json'
    with open(meta_path, 'w') as f:
        json.dump(metadata, f, indent=2)
    print(f"\n  Metadata written to {meta_path}")
    print(f"  {len(metadata)} meshes processed")
    return metadata


if __name__ == "__main__":
    print("CR10 Mesh Pipeline")
    print("=" * 40)
    run_pipeline()
